# Generated by Django 3.2.16 on 2023-03-30 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('BPM', models.FloatField(default=0.0)),
                ('sdnn', models.FloatField(default=0.0)),
                ('rmssd', models.FloatField(default=0.0)),
                ('pnn20', models.FloatField(default=0.0)),
                ('hr_mad', models.FloatField(default=0.0)),
                ('sd1', models.FloatField(default=0.0)),
                ('breathingrate', models.FloatField(default=0.0)),
                ('lf_hf', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date inserted')),
                ('time_stamp', models.IntegerField(default=0)),
                ('ppg_signal', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrv.question')),
            ],
        ),
    ]
